version: '3.8'

services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 8000:80
    depends_on:
      - api
    volumes:
      - static_volume:/api/staticfiles
      - uploaded_files:/api/uploads
  api:
    build: .
    command: /bin/bash /api/bin/boot.sh
    restart: always
    volumes:
      - ./api/:/api
      - static_volume:/api/staticfiles
      - uploaded_files:/api/uploads
    expose:
      - 8001
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=django
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d django -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  static_volume:
  uploaded_files:
