# Generated by Django 4.2.4 on 2023-10-23 15:34

from django.db import migrations, models
import gallery.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=gallery.helpers.thumbnail_upload_directory_name),
        ),
    ]
