# Generated by Django 4.2.4 on 2023-10-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_photo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
