# Generated by Django 4.2.4 on 2023-10-04 14:15

from django.db import migrations, models
import gallery.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_album_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to=gallery.helpers.photo_upload_directory_name),
        ),
    ]
