# Generated by Django 4.2.4 on 2023-10-08 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_album_published_photo_visible_alter_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover', to='gallery.photo'),
        ),
    ]
