# Generated by Django 4.2.4 on 2023-10-09 00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_album_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover',
        ),
        migrations.CreateModel(
            name='AlbumCover',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gallery.album')),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover', to='gallery.photo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
