# Generated by Django 4.2.4 on 2023-10-10 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_remove_album_cover_albumcover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumcover',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='albumcover',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='albumcover',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='albumcover',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gallery.album'),
        ),
    ]
