# Generated by Django 4.2.4 on 2023-10-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_albumcover_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover', to='gallery.photo'),
        ),
        migrations.DeleteModel(
            name='AlbumCover',
        ),
    ]
